In [2]:
import numpy as np

In [6]:
# Write a numpy program to evaluate 2 list.
l1 = np.array([1,2,3,4])
l2 = np.array([5,3,2,7])
gt = np.greater(l1,l2)
lt = np.less(l1,l2)
ge = np.greater_equal(l1,l2)
le = np.less_equal(l1,l2)
eq = np.equal(l1,l2)
print("L1>L2",gt, "\nL1<L2",lt, "\nL1>=L2",ge,"\nL1<=L2",le,"\nL1=L2",eq)

L1>L2 [False False  True False] 
L1<L2 [ True  True False  True] 
L1>=L2 [False False  True False] 
L1<=L2 [ True  True False  True] 
L1=L2 [False False False False]


In [9]:
 # Write a numpy program to generate even number array from 50-90.
l = np.arange(50,91,2)
print(l)

[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90]


In [11]:
# Write a numpy program to generate a 4x4 identity matrix
i = np.identity(4,dtype=int)
print(i)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [12]:
# Write a program to generate a 5x5 0 matrix with elements on main diagonal: 1,2,3,4,5.
d = np.diag([1,2,3,4,5])
print(d)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [26]:
# Write a numpy program to create a vector with the values from 0 to 20 and change the sign of the numbers in the range 9 to 15.
l = np.arange(0,21)
print("Original",l)
for i in l:
    if i>=9 and i<=15:
        l[i]=i*-1
print("After change ",l)    

Original [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After change  [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [31]:
#  Write a numpy program to compute the sum of all elements, sum of each column, and sum of each row for a given array.
a = [[1,2,3],
     [4,5,6]]
ar = np.array(a)

print("Sum of array  : ",ar.sum())
print("Sum of row array  : ",ar.sum(1))
print("Sum of column array  : ",ar.sum(0))



Sum of array  :  21
Sum of row array  :  [ 6 15]
Sum of column array  :  [5 7 9]


In [38]:
n = np.arange(0,21)
with open ("file.txt","w") as f:
    f.write(str(n))
with open ("file.txt","r") as f:
    print(f.readline())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [46]:
a1 = np.array([2,4])
a2 = np.array([3,4])
print(np.equal(a1,a2))

np.array_equal(a1,a2)

[False  True]


False

In [71]:
# Write a numpy program to create a 4x4 array with random values. Create a new array from the set array by swapping 1st and last rows.
import random
l1 = []
for i in range(4):
    l2 = []
    for j in range(4):
        l2.append(random.randint(1,30))
    l1.append(l2)
m1 = np.array(l1)
print("Original\n",m1)
m1[[0, -1]] = m1[[-1, 0]]
print("After swapping \n",m1)

Original
 [[ 4 11 29  5]
 [11  9 11  8]
 [ 6 16  1  5]
 [26 19 29  4]]
After swapping 
 [[26 19 29  4]
 [11  9 11  8]
 [ 6 16  1  5]
 [ 4 11 29  5]]


In [64]:
arr = np.random.randint(1,10,(4,4))
print(arr)

[[4 2 4 9]
 [3 5 1 6]
 [1 2 3 5]
 [6 3 5 8]]


In [65]:
arr = np.random.rand(4,3)
print(arr)

[[0.60279505 0.44299376 0.52343351]
 [0.55608534 0.13985172 0.86418428]
 [0.06065748 0.69045875 0.16716282]
 [0.52588807 0.94808481 0.17383038]]


[[0.51730577 0.71359701 0.09856612]
 [0.18092822 0.13386909 0.15252376]
 [0.28408281 0.92888387 0.47555893]
 [0.28167773 0.63153769 0.84178127]]


In [72]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
print("Product", a1*a2)

Product [ 5 12 21 32]


### Matrix Operations

In [74]:
mat1 = []
mat2 = []

r1, c1 = list(map(int,input("Enter rows and columns of mat 1: ").split()))
r2, c2 = list(map(int, input("Enter rows and column of mat 2 : ").split()))

ele = list(map(int,input("Enter the elements of mat 1: ").split()))
mat1.append(ele)
m1 = np.array(mat1).reshape(r1,c1)

ele = list(map(int,input("Enter the elements of mat 2: ").split()))
mat2.append(ele)
m2 = np.array(mat2).reshape(r2,c2)

print(m1)
print("--------------------")
print(m2)


[[1 2]
 [3 4]]
--------------------
[[1 2]
 [3 4]]


In [78]:
dot = m2.dot(m1)
print("Dot product : ")
print(dot)

Dot product : 
[[ 7 10]
 [15 22]]


In [83]:
print("Transpose")
print(np.transpose(m1))

Transpose
[[1 3]
 [2 4]]


In [82]:
print("Determinant")
print(np.linalg.det(m1))

Determinant
-2.0000000000000004


In [84]:
print("Inverse")
print(np.linalg.inv(m1))

Inverse
[[-2.   1. ]
 [ 1.5 -0.5]]


In [85]:
print("Trace")
print(np.trace(m1))

Trace
5


In [86]:
print("Rank")
print(np.linalg.matrix_rank(m1))

Rank
2


In [87]:
print("Eigen")
print(np.linalg.eig(m1))

Eigen
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
